name: Label Issues

on:
  push:
    issues:
      types: [opened, edited]

jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
    - name: Add labels
      uses: actions/labeler@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yml
